### ISSUE TITLE
Ensure-CosmosSuccess should be part of the module

### ISSUE THREAD

**Issue by adamijak** [GreyCorbel/CosmosLite#2]
`Ensure-CosmosSuccess` should be part of the module

```ps
function Ensure-CosmosSuccess
{
    param
    (
        [Parameter(Mandatory, ValueFromPipeline)]
        $CosmosResult
    )

    process
    {
        if($CosmosResult.IsSuccess)
        {
            $CosmosResult
        }
        else 
        {
            throw [PSCustomObject]@{Code = $CosmosResult.Data.Code; Message = $CosmosResult.Data.message}
        }
    }
}
```

**Comment by jformacek** [comment]
This functionality is already there, and respects `-ErrorAction` standard parameter:
- `Stop`: we throw CosmosLiteException that describes the error
- `Continue`: we write the exception to error output stream and continue processing
- `SilentlyContinue`: we neither throw nor write error and let caller to handle error processing on their own

See internal function `ProcessCosmosResponseInternal` for implementation details

Does it answer the question / address the need?

**Comment by adamijak** [comment]
`-ErrorAction` definitely covers most of the use cases.
In some cases it would be handy to throw the exception lazily after you handle common errors manually.
For example:
```ps1
$rsp = Get-CosmosDocument -Id 'id' -PartitionKey 'pk' -Collection 'col' -ErrorAction SilentlyContinue
if($rsp.HttpCode -eq 404)
{
    $rsp = New-CosmosDocument -DocumentObject $item -PartitionKeyAttribute 'pk' -Collection 'col'
}
else
{
    $rsp | Ensure-CosmosSuccess
}

**Comment by jformacek** [comment]
Implemented new command `Assert-CosmosResult` - see v3.1.1-beta1 release
